version: '3.4'

services:

  database:
    image: custom-postgres:alpine3.17
    build:
      context: ./
      dockerfile: ./database/Dockerfile
    hostname: database
    networks:
      database-tier:
        aliases:
          - database.hotel.com
    environment:
      POSTGRES_USER: app-user
      POSTGRES_PASSWORD: $POSTGRES_PWD
      POSTGRES_DB: hotel-db
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app-user -d hotel-db" ]
      interval: 10s
      timeout: 5s
      retries: 6
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ${DATABASE_SCRIPTS}/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - ${CONFIGURATIONS}/postgresql.conf:/etc/postgresql/postgresql.conf

  hotel-backend:
    image: hotel-backend:latest
    build:
      context: hotel-backend
    depends_on:
      database:
        condition: service_healthy
    hostname: hotel-backend
    healthcheck:
      test: "curl --fail --silent -k https://localhost:8081/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 10s
    ports:
      - '8081:8081'
    environment:
      SPRING_APPLICATION_JSON: '{
        "database.password": "$POSTGRES_PWD",
        "certificates.dir": "/certificates",
        "certificates-password": "$CERTIFICATES_PWD"
      }'
    networks:
      database-tier:
      backend-service-tier:
        aliases:
          - hotel-backend.hotel.com
    volumes:
      - ${CERTIFICATES}/:/certificates

  hotel-rest-api:
    image: hotel-rest-api:latest
    build:
      context: hotel-rest-api
    depends_on:
      hotel-backend:
        condition: service_healthy
    hostname: hotel-rest-api
    healthcheck:
      test: "curl --fail --silent -k https://localhost:8443/api/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 10s
    ports:
      - '8080:8443'
    environment:
      JAVA_OPTS:
        -Djavax.net.ssl.trustStore=/certificates/cacerts
        -Djavax.net.ssl.trustStorePassword=${CERTIFICATES_PWD}
    networks:
      backend-service-tier:
      rest-api-tier:
        aliases:
          - hotel-rest-api.hotel.com
    volumes:
      - ${CERTIFICATES}/:/certificates
      - ${TOMCAT_CONFIG}/server.xml:/usr/local/tomcat/conf/server.xml

  hotel-frontend:
    image: hotel-frontend:latest
    build:
      context: hotel-frontend
    depends_on:
      hotel-rest-api:
        condition: service_healthy
    hostname: hotel-frontend
    ports:
      - '443:8082'
    environment:
      SPRING_APPLICATION_JSON: '{
        "certificates.dir": "/certificates",
        "certificates-password": "$CERTIFICATES_PWD"
      }'
    networks:
      rest-api-tier:
      frontend-tier:
        aliases:
          - hotel-frontend.hotel.com
    volumes:
      - ${CERTIFICATES}/:/certificates

networks:
  database-tier:
  rest-api-tier:
  backend-service-tier:
  frontend-tier: